"""add_medicines_cache_table

Revision ID: 007533fc0709
Revises: 7de9175889de
Create Date: 2026-08-21 09:24:09.145320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007533fc0709'
down_revision: Union[str, Sequence[str], None] = '7de9175889de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('search_term', sa.String(), nullable=False),
    sa.Column('results_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicines_cache_search_term'), 'medicines_cache', ['search_term'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicines_cache_search_term'), table_name='medicines_cache')
    op.drop_table('medicines_cache')
    # ### end Alembic commands ###
