"""Add Indian medicines columns

Revision ID: 3ddb8b288405
Revises: 4bbd22f51103
Create Date: 2026-08-21 10:19:27.257715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddb8b288405'
down_revision: Union[str, Sequence[str], None] = '4bbd22f51103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicines', sa.Column('price_inr', sa.Float(), nullable=True))
    op.add_column('medicines', sa.Column('is_discontinued', sa.Boolean(), nullable=True))
    op.add_column('medicines', sa.Column('manufacturer_name', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('type', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('pack_size_label', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('composition_primary', sa.String(), nullable=True))
    op.add_column('medicines', sa.Column('composition_secondary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicines', 'composition_secondary')
    op.drop_column('medicines', 'composition_primary')
    op.drop_column('medicines', 'pack_size_label')
    op.drop_column('medicines', 'type')
    op.drop_column('medicines', 'manufacturer_name')
    op.drop_column('medicines', 'is_discontinued')
    op.drop_column('medicines', 'price_inr')
    # ### end Alembic commands ###
