"""Add profile_picture to profiles

Revision ID: 404db6afee92
Revises: bc3bab73a74e
Create Date: 2026-08-20 12:19:48.014838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '404db6afee92'
down_revision: Union[str, Sequence[str], None] = 'bc3bab73a74e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('profile_picture', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'profile_picture')
    # ### end Alembic commands ###
