"""add_medicines_table

Revision ID: 4bbd22f51103
Revises: 007533fc0709
Create Date: 2026-08-21 09:46:12.520686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bbd22f51103'
down_revision: Union[str, Sequence[str], None] = '007533fc0709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('generic_name', sa.String(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('dosage_form', sa.String(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('warnings', sa.Text(), nullable=True),
    sa.Column('active_ingredients', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Enable pg_trgm extension and create GIN index for fast partial matches
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")
    op.execute("CREATE INDEX ix_medicines_name_trgm ON medicines USING gin (name gin_trgm_ops);")
    
    op.drop_index(op.f('ix_medicines_cache_search_term'), table_name='medicines_cache')
    op.drop_table('medicines_cache')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicines_cache',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('search_term', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('results_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('medicines_cache_pkey'))
    )
    op.create_index(op.f('ix_medicines_cache_search_term'), 'medicines_cache', ['search_term'], unique=True)
    op.drop_index(op.f('ix_medicines_name'), table_name='medicines')
    op.drop_table('medicines')
    # ### end Alembic commands ###
