"""add frequency and food instructions

Revision ID: 894be51879d0
Revises: 1819030f6ebc
Create Date: 2026-08-21 12:39:19.368079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '894be51879d0'
down_revision: Union[str, Sequence[str], None] = '1819030f6ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_reminders', sa.Column('frequency', sa.String(), nullable=True))
    op.add_column('medicine_reminders', sa.Column('days_of_week', sa.String(), nullable=True))
    op.add_column('medicine_reminders', sa.Column('food_instruction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medicine_reminders', 'food_instruction')
    op.drop_column('medicine_reminders', 'days_of_week')
    op.drop_column('medicine_reminders', 'frequency')
    # ### end Alembic commands ###
