"""add_emergency_contact_email

Revision ID: 8ab43b9e4e84
Revises: 404db6afee92
Create Date: 2026-08-20 14:02:50.160794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ab43b9e4e84'
down_revision: Union[str, Sequence[str], None] = '404db6afee92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('emergency_contact_email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'emergency_contact_email')
    # ### end Alembic commands ###
