"""remove_frequency_add_reminder_logs

Revision ID: bd94a51a61b2
Revises: 8ab43b9e4e84
Create Date: 2026-08-20 20:51:56.294682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd94a51a61b2'
down_revision: Union[str, Sequence[str], None] = '8ab43b9e4e84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reminder_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reminder_id'], ['medicine_reminders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('medicine_reminders', 'frequency')
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medicine_reminders', sa.Column('frequency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('reminder_logs')
    # ### end Alembic commands ###
